# Generated by Django 5.2.3 on 2025-06-25 11:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0002_alter_cook_year_of_experience_alter_dish_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="last_login",
            field=models.DateTimeField(
                blank=True, null=True, verbose_name="last login"
            ),
        ),
    ]
