# Generated by Django 5.2.3 on 2025-07-10 10:12

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("kitchen", "0003_alter_cook_last_login"),
    ]

    operations = [
        migrations.AlterField(
            model_name="cook",
            name="year_of_experience",
            field=models.IntegerField(
                blank=True,
                null=True,
                validators=[django.core.validators.MinValueValidator(1)],
            ),
        ),
    ]
